In [1]:
!pip install numpy

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5])

print(arr1)



[1 2 3 4 5]


In [5]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr2 = np.array([[1, 2, 3], [4, 5, 6]])



print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np

arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [8]:
print(arr3.ndim)

3


In [9]:
import numpy as np

arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[2:3])

[3]


In [10]:

print(arr4[0:4])

[1 2 3 4]
